[package]
name = "jupiter-fsw"
version = "0.1.0"
edition = "2024"

[dependencies]
bin-packets = { git = "https://github.com/Terminus-Suborbital-Research-Program/AMALTHEA.git" }
bincode = "2.0.1"
log = { version = "0.4.26", features = ["std"] }
sqlite = "0.36.2"
